openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Choose Your Own Adventure API"
  description: "An API for a Choose Your Own Adventure game."

servers:
  - url: "https://api.yourwebsite.com"

paths:
  /player:
    post:
      summary: "Create a new player state."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        "201":
          description: "Player state created successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'

  /player/{playerId}:
    patch:
      summary: "Update a player's state by ID."
      parameters:
        - name: "playerId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        "200":
          description: "Player state updated."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
    get:
      summary: "Retrieve a player's state."
      parameters:
        - name: "playerId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Player state retrieved."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'

  /storyElements:
    post:
      summary: "Create a new story element."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoryElement'
      responses:
        "201":
          description: "Story element created successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoryElement'

  /storyElements/{nodeId}:
    get:
      summary: "Retrieve a story node."
      parameters:
        - name: "nodeId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Story node retrieved."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoryElement'
    put:
      summary: "Update a story node by its ID."
      parameters:
        - name: "nodeId"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoryElement'
      responses:
        "200":
          description: "Story element updated."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoryElement'

components:
  schemas:
    Player:
      type: "object"
      properties:
        _id:
          type: "string"  # Updated from object, assuming you'll be interacting with it as a hex string
        wixID:
          type: "string"
          format: "uuid"
        username:
          type: "string"
        email:
          type: "string"
        storyStates:  
          type: "array"
          items:
            type: "object"
            properties:
              storyID:
                type: "string"
              currentChapter:
                type: "string"
              currentPart:
                type: "string"
              wisdoms:
                type: "array"
                items:
                  type: "string"
              artifacts:
                type: "array"
                items:
                  type: "string"

    StoryElement:
      type: "object"
      properties:
        _id:
          type: "string"  # Updated from object, assuming you'll be interacting with it as a hex string
        storyID:
          type: "string"
        nodeID:
          type: "string"
        chapter:
          type: "object"
          properties:
            name:
              type: "string"
            artURL:
              type: "string"
            videoURL:
              type: "string"
        part:
          type: "object"
          properties:
            name:
              type: "string"
            artURL:
              type: "string"
            videoURL:
              type: "string"
        content:
          type: "string"
        options:
          type: "array"
          items:
            type: "object"
        wisdoms:
          type: "array"
          items:
            type: "object"
        artifacts:
          type: "array"
          items:
            type: "object"
