// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Player defines model for Player.
type Player struct {
	Id         *string `json:"_id,omitempty"`
	Email      *string `json:"email,omitempty"`
	StoryState *struct {
		Artifacts      *[]string `json:"artifacts,omitempty"`
		CurrentChapter *string   `json:"currentChapter,omitempty"`
		CurrentPart    *string   `json:"currentPart,omitempty"`
		Wisdoms        *[]string `json:"wisdoms,omitempty"`
	} `json:"storyState,omitempty"`
	Username *string             `json:"username,omitempty"`
	WixID    *openapi_types.UUID `json:"wixID,omitempty"`
}

// StoryElement defines model for StoryElement.
type StoryElement struct {
	Id *struct {
		Oid *string `json:"$oid,omitempty"`
	} `json:"_id,omitempty"`
	Artifacts *[]map[string]interface{} `json:"artifacts,omitempty"`
	Chapter   *struct {
		ArtURL   *string `json:"artURL,omitempty"`
		Name     *string `json:"name,omitempty"`
		VideoURL *string `json:"videoURL,omitempty"`
	} `json:"chapter,omitempty"`
	Content *string                   `json:"content,omitempty"`
	NodeID  *string                   `json:"nodeID,omitempty"`
	Options *[]map[string]interface{} `json:"options,omitempty"`
	Part    *struct {
		ArtURL   *string `json:"artURL,omitempty"`
		Name     *string `json:"name,omitempty"`
		VideoURL *string `json:"videoURL,omitempty"`
	} `json:"part,omitempty"`
	Wisdoms *[]map[string]interface{} `json:"wisdoms,omitempty"`
}

// GetPlayerParams defines parameters for GetPlayer.
type GetPlayerParams struct {
	Id    *string             `form:"id,omitempty" json:"id,omitempty"`
	Wixid *openapi_types.UUID `form:"wixid,omitempty" json:"wixid,omitempty"`
}

// GetStoryElementsParams defines parameters for GetStoryElements.
type GetStoryElementsParams struct {
	NodeId string `form:"nodeId" json:"nodeId"`
}

// PostPlayerJSONRequestBody defines body for PostPlayer for application/json ContentType.
type PostPlayerJSONRequestBody = Player

// PatchPlayerPlayerIdJSONRequestBody defines body for PatchPlayerPlayerId for application/json ContentType.
type PatchPlayerPlayerIdJSONRequestBody = Player

// PostStoryElementsJSONRequestBody defines body for PostStoryElements for application/json ContentType.
type PostStoryElementsJSONRequestBody = StoryElement

// PutStoryElementsNodeIdJSONRequestBody defines body for PutStoryElementsNodeId for application/json ContentType.
type PutStoryElementsNodeIdJSONRequestBody = StoryElement
