// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Player defines model for Player.
type Player struct {
	Id          *string `json:"_id,omitempty" bson:"_id,omitempty"`
	Email       *string `json:"email,omitempty" bson:"email,omitempty"`
	StoryStates *[]struct {
		Artifacts      *[]string `json:"artifacts,omitempty" bson:"artifacts,omitempty"`
		CurrentChapter *string   `json:"currentChapter,omitempty" bson:"currentChapter,omitempty"`
		CurrentPart    *string   `json:"currentPart,omitempty" bson:"currentPart,omitempty"`
		StoryID        *string   `json:"storyID,omitempty" bson:"storyID,omitempty"`
		Wisdoms        *[]string `json:"wisdoms,omitempty" bson:"wisdoms,omitempty"`
	} `json:"storyStates,omitempty" bson:"storyStates,omitempty"`
	Username *string             `json:"username,omitempty" bson:"username,omitempty"`
	WixID    *openapi_types.UUID `json:"wixID,omitempty" bson:"wixID,omitempty"`
}

// StoryElement defines model for StoryElement.
type StoryElement struct {
	Id        *string                   `json:"_id,omitempty" bson:"_id,omitempty"`
	Artifacts *[]map[string]interface{} `json:"artifacts,omitempty" bson:"artifacts,omitempty"`
	Chapter   *struct {
		ArtURL   *string `json:"artURL,omitempty" bson:"artURL,omitempty"`
		Name     *string `json:"name,omitempty" bson:"name,omitempty"`
		VideoURL *string `json:"videoURL,omitempty" bson:"videoURL,omitempty"`
	} `json:"chapter,omitempty" bson:"chapter,omitempty"`
	Content *string                   `json:"content,omitempty" bson:"content,omitempty"`
	NodeID  *string                   `json:"nodeID,omitempty" bson:"nodeID,omitempty"`
	Options *[]map[string]interface{} `json:"options,omitempty" bson:"options,omitempty"`
	Part    *struct {
		ArtURL   *string `json:"artURL,omitempty" bson:"artURL,omitempty"`
		Name     *string `json:"name,omitempty" bson:"name,omitempty"`
		VideoURL *string `json:"videoURL,omitempty" bson:"videoURL,omitempty"`
	} `json:"part,omitempty" bson:"part,omitempty"`
	StoryID *string                   `json:"storyID,omitempty" bson:"storyID,omitempty"`
	Wisdoms *[]map[string]interface{} `json:"wisdoms,omitempty" bson:"wisdoms,omitempty"`
}


// PostPlayerJSONRequestBody defines body for PostPlayer for application/json ContentType.
type PostPlayerJSONRequestBody = Player

// PatchPlayerPlayerIdJSONRequestBody defines body for PatchPlayerPlayerId for application/json ContentType.
type PatchPlayerPlayerIdJSONRequestBody = Player

// PostStoryElementsJSONRequestBody defines body for PostStoryElements for application/json ContentType.
type PostStoryElementsJSONRequestBody = StoryElement

// PutStoryElementsNodeIdJSONRequestBody defines body for PutStoryElementsNodeId for application/json ContentType.
type PutStoryElementsNodeIdJSONRequestBody = StoryElement
