name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main  # The branch on which to trigger the workflow

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: cyoa-api-cluster  # Customize with your cluster name
  GKE_ZONE: us-central1  # Customize with your zone
  IMAGE: gcr.io/choose-your-own-dbt-adventure/cyoa-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Kubernetes Cluster
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        
    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to GKE
      run: |
        kubectl apply -f manifest.yaml  # Replace manifest.yaml with the path to your Kubernetes manifest if different

